---
stages:
  - publish

image: maven:3.8.1-jdk-8

maven build:
  stage: publish
  before_script:
    - apt update && apt install patch
  script:
    - git config --global user.name 'KIG CI Builds'
    - git config --global user.email 'contact+ci-builds@playkig.com'
    - git submodule update --init
    - ./remap.sh &&./decompile.sh && ./init.sh && ./newApplyPatches.sh
    - cp server_ci_pom.xml PaperSpigot-Server/pom.xml
    - cp api_ci_pom.xml PaperSpigot-API/pom.xml
    - mvn package deploy -f ci_pom.xml -s ci_settings.xml
...
